name: CI

on:
  push:
    branches: [ "homework1" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GTest Install
      run: sudo apt install libgtest-dev
    - name: CMake Init
      working-directory: homework1
      run: cmake . -B ./build/
    - name: CMake Execute
      working-directory: homework1/build
      run: cmake --build .
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      working-directory: homework1/build
      run: ./helloworld_test

      
